services:
    scim: true
    proxy: true
    ssf: true
    hooks: true
    dpop: false
redis:
    # address: localhost:6379
    address: redis-scim:6379
    password: ""
    db: 0
server:
    address: ":8082"
    public_address: "http://localhost:8082"
    web_address: ":8080"
    web_console: true
    debug_headers: false
    debug_body: false
    debug_query: false
    log_messages: false
    proxy_messages: false
    proxy_address: ":8084"
    filter_ips: false
    okta_public_ips_url: "https://s3.amazonaws.com/okta-ip-ranges/ip_ranges.json"
    unauthorized_ips_oauth_config:
        issuer: "https://{org}.oktapreview.com/oauth2/default"
        client_id: "0oa..."
        client_secret: "BBf..."
        scopes: "openid profile email go_scim"
        redirect_uri: "http://localhost:8082/authorizeMyIp/callback"
scim:
    enable_groups: true
    users_endpoint: "/goscim/scim/v2/Users"
    groups_endpoint: "/goscim/scim/v2/Groups"
ssf:
    transmitter_config:
        issuer: "https://gw.oktamanor.net"
        jwks_uri: "https://gw.oktamanor.net:8443/ssf/transmitter/keys"
        configuration_endpoint: "https://gw.oktamanor.net:8443/ssf/transmitter/stream"
build: "v2.11.000"